version: '3.7'

services:
  # ------------------------------------------------------------
  # Redis
  # ------------------------------------------------------------
  redis:
    image: redis:6.0.16
    user: "${UID}:${GID}"
    env_file:
      - ./.env

    command: redis-server /usr/local/etc/redis/redis.conf

    ports:
      - "6379:6379"
      
    volumes:
      - ./conf/redis:/usr/local/etc/redis:ro,delegated
      - ./data/redis:/data:rw,delegated


  # ------------------------------------------------------------
  # SIC desktop devices
  # ------------------------------------------------------------
  sic:
    image: sic_python
    build:
      context: .
      dockerfile: Dockerfile_SIC.python3

    env_file:
      - ./.env

    depends_on:
      - redis

  # ------------------------------------------------------------
  # Depth estimation
  # ------------------------------------------------------------
  depth_estimation:
    image: sic_python

    env_file:
      - ./.env

    command: python3 sic/sic_framework/services/depth_estimation/depth_estimation_service.py

    depends_on:
      - sic

  # ------------------------------------------------------------
  # Dialogflow
  # ------------------------------------------------------------
  dialogflow:
    image: sic_python

    env_file:
      - ./.env

    command: python3 sic/sic_framework/services/dialogflow/dialogflow_service.py

    depends_on:
      - sic

  # ------------------------------------------------------------
  # Face detection
  # ------------------------------------------------------------
  face_detection:
    image: sic_python

    env_file:
      - ./.env

    command: python3 sic/sic_framework/services/face_detection/face_detection_service.py

    depends_on:
      - sic

  # ------------------------------------------------------------
  # Face recognition
  # ------------------------------------------------------------
  face_recognition:
    image: sic_python_gpu
    build:
      context: .
      dockerfile: Dockerfile_SIC_gpu.python3

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

    env_file:
      - ./.env

    command: python3 sic/sic_framework/services/face_recognition_dnn/face_recognition_service.py

    depends_on:
      - sic

  # ------------------------------------------------------------
  # Text2Speech
  # ------------------------------------------------------------
  text2speech:
    image: sic_python

    env_file:
      - ./.env

    command: python3 sic/sic_framework/services/text2speech/text2speech_service.py

    depends_on:
      - sic